[tool.poetry]
name = "circuitsvis"
version = "1.1.2"
description = "Mechanistic Interpretability Visualizations"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.20"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
snapshottest = "^0.6.0"
twine = "^4.0.1"
jupyterlab = "^3.5.0"
mypy = "^0.990"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
